### ISSUE TITLE
"Unable to parse ocaml outpuut, expected 3 matches, got 4"

### ISSUE THREAD

**Issue by AlexisWu-01** [olin/focstest#15]
Hey not sure what happened but this parsed thing appeared several times in my teste :)

./focstest.py:131: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("Unable to parse ocaml output, expected 2 matches, got {}".format(len(matches)))
Unable to parse ocaml output, expected 2 matches, got 4
Skipped test 5 of 5 in suite 9: Unable to parse output

**Comment by newsch** [comment]
Yikes, that's not a very helpful warning (my fault).

The `DeprecationWarning` should be fixed with 75eab53a5c25042d698a05d89182ab122ece635f, and #11 is related to improving the warning message.

In this case, it most likely means that there's a syntax error in your ocaml file. The code in `focstest` that parses test outputs doesn't (yet) recognize that there's been an error or exception, only that it doesn't understand the output.
